2021-10-25 09:34:23,639 - INFO - 登录测试
2021-10-25 09:34:24,301 - DEBUG - 登录失败，用户名或密码输出有误！
2021-10-25 09:34:24,924 - DEBUG - 登录失败，用户名或密码输出有误！
2021-10-25 09:34:25,543 - DEBUG - 登录失败，用户名或密码输出有误！
2021-10-25 09:34:26,157 - DEBUG - 登录失败，用户名或密码输出有误！
2021-10-25 15:35:19,302 - INFO - 登录测试
2021-10-25 15:35:19,953 - DEBUG - 登录失败，用户名或密码输出有误！
2021-10-25 15:35:20,583 - DEBUG - 登录失败，用户名或密码输出有误！
2021-10-25 15:35:21,195 - DEBUG - 登录失败，用户名或密码输出有误！
2021-10-25 15:35:21,810 - DEBUG - 登录失败，用户名或密码输出有误！
2021-10-25 15:35:23,677 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 63, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "D:\Code\Selenium\SE_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\Code\Selenium\SE_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Code\Selenium\SE_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

